### ISSUE TITLE
Re-organize sections

### ISSUE THREAD

**Issue by westerandr** [Samoa-Stack-Overflow/sso-website#33]
**Is your feature request related to a problem? Please describe.**
Some of the sections are jumbled up in order.

**Describe the solution you'd like**
I would like the order of sections to be the following:
1. Hero Section
2. About Us Section (What we do and then SSO Timeline)
3. Media Section
4. Contributors Section
5. Contact Us Section

**Comment by tausani-ah-chong** [comment]
Malo le soifua! Im keen to jump onto this, but when I try push my branch I get this `git error`:

```
remote: Permission to Samoa-Stack-Overflow/sso-website.git denied to tausani-ah-chong.
fatal: unable to access 'https://github.com/Samoa-Stack-Overflow/sso-website.git/': The requested URL returned error: 403
```

**Comment by westerandr** [comment]
Hey uso! Thanks for volunteering to contribute 🙌 will have a look at your PR 🙂 

Not sure if you heard about SSO, but if you would like to join, here's our form to fill out: https://forms.gle/aoTeV9jF5h7wnqAG6

We meet up on discord every 2 weeks to discuss the sso website, till it's done!

**Comment by tausani-ah-chong** [comment]
Thanks for the invite uce! I haven't heard but seen yours and @Green-Ranger11 on my feed, and I had a little peek 😂

Keen to join but not sure if I could commit to meeting every 2 weeks. Will try my best otherwise

**Comment by westerandr** [comment]
No worries uso! We're just a group of local programmers from Samoa. No worries about committing to the meetings, we're pretty chill. As long as you're keen to contribute haha
